platform:
    - x64

install:
    # The x64 is required as a workaround for esy/esy#412
    - ps: Install-Product node 8 x64
    - npm install -g esy@0.1.20
    - mkdir C:/projects/ocaml-prefix
    - git clone https://github.com/esy-ocaml/ocaml
    - cd ocaml
    - git checkout 4.6.0+esy

build_script:
    - esy-bash ./esy-configure -no-cfi -prefix C:/projects/ocaml-prefix
    - esy-bash ./esy-build

test: off
